
services:
  k6:
    image: grafana/k6:latest
    container_name: k6-runner
    dns: 8.8.8.8  # Explicit DNS server
    dns_search: .
    volumes:
      - ./k6/scripts:/scripts
    depends_on:
      - influxdb
    environment:
      - K6_OUTFLUXDB_URL=http://influxdb:8086/k6db
      - K6_OUTFLUXDB_USERNAME=k6
      - K6_OUTFLUXDB_PASSWORD=k6pass
    networks:
      k6-net:
        aliases:
          - k6.local

  influxdb:
    image: influxdb:1.8.10
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6db
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
      - INFLUXDB_USER=k6
      - INFLUXDB_USER_PASSWORD=k6pass
      - INFLUXDB_HTTP_WRITE_TIMEOUT=30s
      - INFLUXDB_DATA_CACHE_MAX_MEMORY_SIZE=256m
      - INFLUXDB_HTTP_FLUX_ENABLED=false   # Disable if not needed
      - INFLUXDB_DATA_QUERY_LOG_ENABLED=false  # Reduce logging overhea
    volumes:
      - ./init-influx.sh:/docker-entrypoint-initdb.d/init-influx.sh
      - influxdb-data:/var/lib/influxdb
    networks:
      k6-net:
        aliases:
          - influxdb.local

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning  # Optional: auto provision
    networks:
      k6-net:
        aliases:
          - grafana.local

networks:
  k6-net:
    driver: bridge
    name: k6-load-test-net
    attachable: true
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
    driver_opts:
      com.docker.network.driver.mtu: 1500
      com.docker.network.bridge.enable_icc: "true"

volumes:
  influxdb-data:
  grafana-data:
