apiVersion: 1

datasources:
- name: InfluxDB
  type: influxdb
  access: proxy
  url: http://influxdb:8086
  database: k6db
  user: k6
  secureJsonData:
    password: "k6pass"
  jsonData:
    httpMode: "GET"
    timeInterval: "5s"
  isDefault: true
